add_newline = false
scan_timeout = 10
command_timeout = 1200

format = """
$username\
$hostname\
$localip\
$singularity\
$kubernetes\
[î‚º](bg:#1E1E2E fg:#45475a)\
$directory\
"""
right_format = """
$php\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$jobs\
$battery\
$status\
$container\
$shell\
"""

[character]
#error_symbol = "[â¯](bold red)"
#success_symbol = "[â¯](bold green)"


[aws]
symbol = "îŒ½  "
style = "bg: fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[buf]
symbol = "ï’ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[c]
symbol = "î˜ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[conda]
symbol = "ï„Œ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[dart]
symbol = "î˜ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[directory]
#read_only = " ï ½"
style = "bg:#45475a fg:#f8f8f2"
format = "[ $path ]($style)[î‚° ](fg:#45475a)"
truncation_length = 3
truncation_symbol = "../"


[docker_context]
symbol = "ïŒˆ "
style = "bg:#bd93f9 fg:#45475a"
format = "[$symbol$context]($style)"


[elixir]
symbol = "î‰µ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[elm]
symbol = "î˜¬ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[git_branch]
symbol = "ï˜ "
style = "bg:#f1fa8c fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#f1fa8c)[ $symbol $branch(:$remote_branch) ]($style)"

[git_status]
style = "bg:#f1fa8c fg:#45475a"
format = '[ $all_status$ahead_behind ]($style)[î‚²](bg:#f1fa8c fg:#1E1E2E)'


[golang]
symbol = "î˜§ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[guix_shell]
symbol = "ïŒ¥ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[haskell]
symbol = "î· "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[haxe]
symbol = "âŒ˜ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[java]
symbol = "î·¤ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[julia]
symbol = "î˜¤ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[lua]
symbol = "î˜  "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[memory_usage]
symbol = "ï¡š "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[meson]
symbol = "ï¨¶ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[nim]
symbol = "ïš¤ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[nix_shell]
symbol = "ïŒ“ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[nodejs]
symbol = "îœ˜ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ï¯‘ "
Gentoo = "ïŒ "
HardenedBSD = "ï²Š "
Illumos = "ïœ· "
Linux = "ïŒš "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ïœ¹ "
openSUSE = "ïŒ” "
OracleLinux = "ï ¶ "
Pop = "îŠ£ "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ï”— "
Solus = "ï´± "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ï¡± "


[package]
symbol = "ï£– "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[python]
symbol = "îˆµ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ($virtualenv) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[rlang]
symbol = "ï³’ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[ruby]
symbol = "î‘ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[rust]
symbol = "î¨ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[scala]
symbol = "îœ· "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[spack]
symbol = "ğŸ…¢ "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

[php]
symbol = "î£« "
style = "bg:#bd93f9 fg:#45475a"
format = "[î‚²](bg:#1E1E2E fg:#bd93f9)[ $symbol($version) ]($style)[î‚²](bg:#bd93f9 fg:#1E1E2E)"

